### ISSUE TITLE
Set up Tailwind Css Crashing

### ISSUE THREAD

**Issue by caio-delgado** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#31]
I've been using the extension for a while and it was working really well until I tried cloning my repo to a fresh local folder. Now when I try to setup tailwind through the context menu it produces the following:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
   at System.Text.Json.JsonSerializerOptions.GetOrCreateDefaultOptionsInstance()
   at System.Text.Json.JsonSerializerOptions.get_Default()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<OverrideSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.SetUpTailwind.<ExecuteAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Community.VisualStudio.Toolkit.BaseCommand.<>c__DisplayClass8_0.<<Execute>b__0>d.MoveNext()

Can you help me get it working again? I have tried uninstalling the extension and installling it again but no luck.

**Comment by theron-wang** [comment]
Sorry about that! It looks like I forgot to update one of the related NuGet packages; it should now be working in the latest extension update.

**Comment by theron-wang** [comment]
No problem! It does look like I still referenced an incorrect version of `System.Text.Json` in the current version (VS ships with Microsoft.Bcl.AsyncInterfaces 6.0.0 and 7.0.0 is not shipped in the extension) which is why you still got the error. I have downgraded System.Text.Json to 6.0.9 so there shouldn't be anymore errors regarding missing dependencies.

If you run into any issues, please let me know!

Sorry for the inconvenience, and thanks for letting me know!

**Comment by caio-delgado** [comment]
Just reinstalled and it worked! Thanks for your quick response! This extension is awesome.
