### ISSUE TITLE
Cannot parse tailwindcss-3d

### ISSUE THREAD

**Issue by v36u** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#65]
Hello!

First of all, thank you for this awesome extension and for the time & effort put in! It is very useful!

After having successfully installed https://github.com/sambauers/tailwindcss-3d (meaning the classes generated correctly), I noticed the IntelliSense did not pick up the classes from the `tailwindcss-3d` plugin.

<details>
<summary>Here is the error this extension throws in the output window</summary>

```
System.InvalidOperationException: Error occurred while parsing configuration file: <project_path>\node_modules\tailwindcss-3d\index.js:32
        localAPI.addDefaults('transform', DEFAULT_VARIABLE_VALUES);
                 ^
TypeError: localAPI.addDefaults is not a function
    at <project_path>\node_modules\tailwindcss-3d\index.js:32:18
    at handler ([stdin]:14:64)
    at [stdin]:131:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> ([stdin]:130:27)
    at JSON.stringify (<anonymous>)
    at [stdin]:125:27
    at [stdin]:245:7
    at [stdin]:246:3
    at runScriptInThisContext (node:internal/vm:209:10)
Node.js v20.14.0
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<ReloadCustomAttributesAsync>d__44.MoveNext()
```
</details>

<details>
<summary>`index.js` from `node_modules` looks like this</summary>

```js
"use strict";
var _interop_require_default = require("@swc/helpers/_/_interop_require_default");
var _object_spread = require("@swc/helpers/_/_object_spread");
var _plugin = /*#__PURE__*/ _interop_require_default._(require("tailwindcss/plugin"));
var _cssanimations = require("./css-animations");
var _cssutilities = require("./css-utilities");
var _ensure = require("./utils/ensure");
// Default CSS variables, modelled from core
var DEFAULT_VARIABLE_VALUES = {
    '--tw-perspective': 'none',
    '--tw-translate-x': '0',
    '--tw-translate-y': '0',
    '--tw-translate-z': '0',
    '--tw-rotate-x': '0',
    '--tw-rotate-y': '0',
    '--tw-rotate-z': '0',
    '--tw-skew-x': '0',
    '--tw-skew-y': '0',
    '--tw-scale-x': '1',
    '--tw-scale-y': '1',
    '--tw-scale-z': '1'
};
var optionDefaults = {
    legacy: false
};
var tailwindCss3d = _plugin.default.withOptions(function() {
    var _ref = arguments.length > 0 && arguments[0] !== void 0 ? arguments[0] : optionDefaults, _ref_legacy = _ref.legacy, legacy = _ref_legacy === void 0 ? optionDefaults.legacy : _ref_legacy;
    var safeLegacy = (0, _ensure.ensureBoolean)(legacy, optionDefaults.legacy);
    return function(api) {
        var localAPI = api;
        // Replace the transform core plugin defaults and add some new ones
        localAPI.addDefaults('transform', DEFAULT_VARIABLE_VALUES);
        var perspective = new _cssutilities.Perspective(localAPI, safeLegacy);
        var transformStyle = new _cssutilities.TransformStyle(localAPI);
        var translate = new _cssutilities.Translate(localAPI, safeLegacy);
        var transform = new _cssutilities.Transform(localAPI, safeLegacy);
        var scale = new _cssutilities.Scale(localAPI, safeLegacy);
        var backface = new _cssutilities.Backface(localAPI);
        var perspectiveOrigin = new _cssutilities.PerspectiveOrigin(localAPI);
        var transformBox = new _cssutilities.TransformBox(localAPI);
        var transformCore = new _cssutilities.TransformCore(localAPI, safeLegacy);
        // New CSS Utilities
        perspective.utilities();
        transformStyle.utilities();
        translate.utilities();
        transform.utilities();
        scale.utilities();
        backface.utilities();
        perspectiveOrigin.utilities();
        transformBox.utilities();
        transformCore.utilities();
    };
}, function() {
    var _ref = arguments.length > 0 && arguments[0] !== void 0 ? arguments[0] : optionDefaults, _ref_legacy = _ref.legacy, legacy = _ref_legacy === void 0 ? optionDefaults.legacy : _ref_legacy;
    var safeLegacy = (0, _ensure.ensureBoolean)(legacy, optionDefaults.legacy);
    var spin = new _cssanimations.Spin(safeLegacy);
    var bounce = new _cssanimations.Bounce(safeLegacy);
    var bounceAndSpin = new _cssanimations.BounceAndSpin(safeLegacy);
    return {
        theme: {
            // Set new theme defaults
            perspective: _cssutilities.Perspective.defaultTheme,
            transformStyle: _cssutilities.TransformStyle.defaultTheme,
            backface: _cssutilities.Backface.defaultTheme,
            perspectiveOrigin: _cssutilities.PerspectiveOrigin.defaultTheme,
            transformBox: _cssutilities.TransformBox.defaultTheme,
            spin: spin.defaultTheme,
            bounce: bounce.defaultTheme,
            bounceAndSpin: bounceAndSpin.defaultTheme,
            extend: {
                // Update the core transform transition property
                transitionProperty: {
                    transform: safeLegacy ? 'transform' : 'perspective, translate, scale, transform, perspective, rotate'
                },
                // New CSS keyframes and animations
                keyframes: function(pluginUtilities) {
                    return _object_spread._({}, spin.keyframes(), bounce.keyframes(pluginUtilities), bounceAndSpin.keyframes(pluginUtilities));
                },
                animation: function(pluginUtilities) {
                    return _object_spread._({}, spin.animation(pluginUtilities), bounce.animation(pluginUtilities), bounceAndSpin.animation(pluginUtilities));
                }
            }
        },
        // Disable some core plugins which are superceded by this plugin
        corePlugins: {
            rotate: false,
            scale: false,
            skew: false,
            transform: false,
            translate: false
        }
    };
});
module.exports = tailwindCss3d;
```
</details>

**Comment by theron-wang** [comment]
@v36u No problem! Thank you for reporting the bug.

A fix should now be available in 1.5.2. The issue was simple: the configuration file parser for the extension lacked the `addDefaults` method for Tailwind plugins. If you still encounter the issue, please let me know!
