### ISSUE TITLE
Tailwind Extension Failed to load

### ISSUE THREAD

**Issue by li-acardenas** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#68]
Hi, the extension is failing to load when i start Visual studio 2022

here is the trace im getting in the extension output window

System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<OverrideSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<GetSettingsAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Build.TailwindBuildProcess.<InitializeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.TailwindCSSIntellisensePackage.<<InitializeAsync>b__6_0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<OverrideSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<GetSettingsAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Build.TailwindBuildProcess.<InitializeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.TailwindCSSIntellisensePackage.<<InitializeAsync>b__6_0>d.MoveNext()

**Comment by InfGame** [comment]
For me VS 2022 is just stuck in a loop trying to open my project. can only fix with a repair of VS

**Comment by theron-wang** [comment]
@li-acardenas This might be an issue with installation; sometimes the extension is downloaded without the correct dependencies so I would retry that if the issue is urgent. If that doesn’t work, I can try to explicitly include the missing DLLs in the extension when I get the chance.

**Comment by theron-wang** [comment]
@InfGame I’m not sure if your issue is directly related to this issue (unless the logs say so?). If possible, could you check the VS Activity Logs (located in `%AppData%\Microsoft\VisualStudio\{version}\ActivityLog.xml` to see if there are any logs that include `Tailwind`? If there are, I would appreciate it if you could open a new issue with the relevant logs. Thanks!

**Comment by InfGame** [comment]
> @InfGame I’m not sure if your issue is directly related to this issue (unless the logs say so?). If possible, could you check the VS Activity Logs (located in `%AppData%\Microsoft\VisualStudio\{version}\ActivityLog.xml` to see if there are any logs that include `Tailwind`? If there are, I would appreciate it if you could open a new issue with the relevant logs. Thanks!

@theron-wang I don't see a ActivityLog.xml in the given directory.

**Comment by InfGame** [comment]
I am using it in combination with the EF Core Power Tools extension. maybe there is a conflict?

**Comment by InfGame** [comment]
@theron-wang alright, after some testing on my own I found out that, if I open visual studio by clicking on the .sln in my project directly it gets stuck in the loading loop. but if i open VS without opening the project and then open it via the project selection page it works perfectly fine.

**Comment by theron-wang** [comment]
@li-acardenas I've packaged the DLL in the 1.5.5 version of the extension. If there is still an issue, please let me know. Thanks!

**Comment by theron-wang** [comment]
@InfGame 

> I don't see a ActivityLog.xml in the given directory. There is only a ActivityLog.Setup.xml and it does not have any references to tailwind

Sorry about that, I didn't realize that `ActivityLog.xml` doesn't normally generate (i.e. it does when debugging extensions, however).

> I am using it in combination with the EF Core Power Tools extension. maybe there is a conflict?

I don't believe that they would conflict with each other, given that the two extensions do not target the same VS features (based on a quick glance on their codebase).

I'm not necessarily sure that this is an issue with this extension or rather one with VS itself; I've encountered this issue several times and I wasn't able to link it back to this extension (when I encountered this issue, a breakpoint set in the initializing method of the extension was never hit). If possible, could you disable the extension and see if the issue still persists? We should also move this to a new issue since I don't believe that the cases are related. Thanks!
