### ISSUE TITLE
Tailwind config `content.transform` causes extension to fail loading

### ISSUE THREAD

**Issue by EirikFA** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#77]
In order for [`@tailwindcss/container-queries`](https://github.com/tailwindlabs/tailwindcss-container-queries) to work, adding a transformer for Razor is required since the @'s used by the plugin have to be escaped (with `@@`) in Razor. The configuration then looks like this:
```js
content: {
  files: ["./Views/**/*.cshtml"],
  transform: {
    cshtml: content => content.replace(/@@/g, "@"),
  }
}
```
However, this causes the extension to fail to load with the following trace:
```
TypeError: content.replace is not a function
    at cshtml (C:\...\tailwind.config.cjs:6:40)
    at Object.<anonymous> (c:\...\appdata\local\microsoft\visualstudio\17.0_ad8f40b8\extensions\5ixbhpjg.ksm\Resources\parser.js:364:58)
    at JSON.stringify (<anonymous>)
    at c:\...\appdata\local\microsoft\visualstudio\17.0_ad8f40b8\extensions\5ixbhpjg.ksm\Resources\parser.js:167:27
    at c:\...\appdata\local\microsoft\visualstudio\17.0_ad8f40b8\extensions\5ixbhpjg.ksm\Resources\parser.js:372:7
    at Object.<anonymous> (c:\...\appdata\local\microsoft\visualstudio\17.0_ad8f40b8\extensions\5ixbhpjg.ksm\Resources\parser.js:373:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
Node.js v20.11.1
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<ReloadCustomAttributesAsync>d__47.MoveNext()
```

**Comment by theron-wang** [comment]
Thank you! This should be fixed in 1.6.2.
