### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by caio-delgado** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#83]
Hey Theron how is going? Here I am again with some new dumps:

This is from the Build Output:
Tailwind CSS: Error: Cannot find module 'arg'

This is from the Extensions Output:
System.InvalidOperationException: Error occurred while parsing configuration file: node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^
Error: Cannot find module 'postcss-js'
Require stack:
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\Client\tailwind.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.require (c:\users\c065708\appdata\local\microsoft\visualstudio\17.0_1b91b02f\extensions\kqlg5jyb.pr2\Resources\parser.js:37:36)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\node_modules\\daisyui\\src\\index.js',
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\Client\\tailwind.config.js'
  ]
}
Node.js v21.2.0
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<InitializeAsync>d__46.MoveNext()
System.InvalidOperationException: Error occurred while parsing configuration file: node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^
Error: Cannot find module 'postcss-js'
Require stack:
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\Client\tailwind.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.require (c:\users\c065708\appdata\local\microsoft\visualstudio\17.0_1b91b02f\extensions\kqlg5jyb.pr2\Resources\parser.js:37:36)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\node_modules\\daisyui\\src\\index.js',
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\Client\\tailwind.config.js'
  ]
}
Node.js v21.2.0
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<InitializeAsync>d__46.MoveNext()
System.InvalidOperationException: Error occurred while parsing configuration file: node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^
Error: Cannot find module 'postcss-js'
Require stack:
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\Client\tailwind.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.require (c:\users\c065708\appdata\local\microsoft\visualstudio\17.0_1b91b02f\extensions\kqlg5jyb.pr2\Resources\parser.js:37:36)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\node_modules\\daisyui\\src\\index.js',
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\Client\\tailwind.config.js'
  ]
}
Node.js v21.2.0
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<InitializeAsync>d__46.MoveNext()
System.InvalidOperationException: Error occurred while parsing configuration file: node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^
Error: Cannot find module 'postcss-js'
Require stack:
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\Client\tailwind.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.require (c:\users\c065708\appdata\local\microsoft\visualstudio\17.0_1b91b02f\extensions\kqlg5jyb.pr2\Resources\parser.js:37:36)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\node_modules\\daisyui\\src\\index.js',
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\Client\\tailwind.config.js'
  ]
}
Node.js v21.2.0
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<ReloadCustomAttributesAsync>d__47.MoveNext()
System.InvalidOperationException: Error occurred while parsing configuration file: node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^
Error: Cannot find module 'postcss-js'
Require stack:
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\Client\tailwind.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.require (c:\users\c065708\appdata\local\microsoft\visualstudio\17.0_1b91b02f\extensions\kqlg5jyb.pr2\Resources\parser.js:37:36)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\node_modules\\daisyui\\src\\index.js',
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\Client\\tailwind.config.js'
  ]
}
Node.js v21.2.0
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<ReloadCustomAttributesAsync>d__47.MoveNext()
System.InvalidOperationException: Error occurred while parsing configuration file: node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^
Error: Cannot find module 'postcss-js'
Require stack:
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js
- C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\Client\tailwind.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module.require (c:\users\c065708\appdata\local\microsoft\visualstudio\17.0_1b91b02f\extensions\kqlg5jyb.pr2\Resources\parser.js:37:36)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Desenvolvimento\.NET 6\ToolKitNsgdWeb\node_modules\daisyui\src\index.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\node_modules\\daisyui\\src\\index.js',
    'C:\\Desenvolvimento\\.NET 6\\ToolKitNsgdWeb\\Client\\tailwind.config.js'
  ]
}
Node.js v21.2.0
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<ReloadCustomAttributesAsync>d__47.MoveNext()

**Comment by caio-delgado** [comment]
This one was on me. Reinstalled postcss via npm and it fixed it. Sorry!
