### ISSUE TITLE
Add Tailwind v4 support

### ISSUE THREAD

**Issue by theron-wang** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#85]

**Comment by pm64** [comment]
@theron-wang 4.0 has now been officially released, just wondering if you have a time frame in mind for completion of this task?

**Comment by theron-wang** [comment]
@pm64 Ideally, I’m aiming for sometime in the next two weeks. I haven’t had much time to put into supporting 4.0, but I will try to prioritize this.

**Comment by pm64** [comment]
Thanks for the update @theron-wang, immensely grateful for all you do.

**Comment by theron-wang** [comment]
V4 support added, though some features are not supported yet. A full list can be found in the [changelog](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/blob/main/CHANGELOG.md), and an upgrade guide can be found [here](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/blob/main/Upgrade-Guide.md). I will update this issue as I continue to add more features. If you notice any bugs/missing features, feel free to create a new issue :)

**Comment by skttl** [comment]
Is it supposed to read custom theme values from the css too?

I have this setup:

UI/CSS/main.css:
```css
@import 'tailwindcss';
@import './_theme.css';
...
```

UI/CSS/_theme.css:
```css
@theme {
  /* Colors */
  --color-primary: #226fc4;
...
```

tailwind.extension.json
```json
{
  "$schema": "https://raw.githubusercontent.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/refs/heads/main/tailwind.extension.schema.json",
  "ConfigurationFiles": [
    {
      "Path": "UI\\CSS\\main.css",
      "IsDefault": true,
      "ApplicableLocations": []
    }
  ],
  "BuildFiles": [
    {
      "Input": "UI\\CSS\\main.css",
      "Output": "wwwroot\\css\\main.css"
    }
  ],
  "PackageConfigurationFile": "package.json",
  "CustomRegexes": {
    "Razor": {
      "Override": false,
      "Values": []
    },
    "HTML": {
      "Override": false,
      "Values": []
    },
    "JavaScript": {
      "Override": false,
      "Values": []
    }
  },
  "UseCli": false
}
```

But I don't get intellisense suggestions for eg. the primary color, eg. `bg-primary`, `text-primary` etc.

I have version 1.10.2 installed

There is no output in the output panel for extensions either...

**Comment by skttl** [comment]
If I move my `@theme` directive to `main.css` it seems to be able to set the preview color correctly, but Intellisense fails. I now get output in the Extensions output though.

```
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<>c.<LoadIndividualConfigurationExtend>b__27_1(TailwindClass x, TailwindClass y)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.LoadIndividualConfigurationExtend(ProjectCompletionValues project, TailwindConfiguration config)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<ReloadCustomAttributesImplAsync>d__22.MoveNext()
```

**Comment by skttl** [comment]
This theme var is the problem, if I remove it, it works. As long as the @theme directive is in my main config file

```css
--color-block-background: var(--block-bg, var(--color-background));
```

Is it possible for it to read through imports, so I can have theme variables, plugin setup, custom variants etc. in seperate files?

**Comment by theron-wang** [comment]
@skttl 
> Is it supposed to read custom theme values from the css too?

This wasn't a feature I included in the initial release, but I just added support in 1.10.3.

As for the `InvalidOperationException`, I wasn't able to repro but I did find and fix a `FormatException` arising from the same piece of css you included, so I'm not sure if that fix also addresses your issue.

**Comment by skttl** [comment]
It works - thanks!

Not sure if its possible, but would be nice, if it could update definitions when I save the imported files too. Currently it only updates when I save the input file.

So in my case, where I have main.css as the input, and theme.css imported into main.css, the definitions used for intellisense is only updated if I save main.css after changing theme.css.

Also, I have an import using a layer (`@import './_components.css' layer(components);`) that breaks the plugin, and outputs this:

```
System.IO.FileNotFoundException: Could not find file 'C:\Workspaces\Dinex\Dinex\Presentation\Website\UI\CSS\_components.css layer(components)'.
File name: 'C:\Workspaces\Dinex\Dinex\Presentation\Website\UI\CSS\_components.css layer(components)'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetCssConfigurationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetCssConfigurationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<ReloadCustomAttributesImplAsync>d__22.MoveNext()
```

**Comment by theron-wang** [comment]
@skttl Both should be addressed in 1.10.4. Let me know if there is anything else - thanks.

**Comment by skttl** [comment]
This is great! Thanks!
